import { createVar } from "@vanilla-extract/css";

export const cols = createVar();
export const colsBase = createVar();
export const colsPhone = createVar();
export const colsTablet = createVar();
export const colsLaptop = createVar();
export const colsDesktop = createVar();
export const colsWide = createVar();
export const spacingX = createVar();
export const spacingY = createVar();
export const justify = createVar();
export const span = createVar();
export const spanBase = createVar();
export const spanPhone = createVar();
export const spanTablet = createVar();
export const spanLaptop = createVar();
export const spanDesktop = createVar();
export const spanWide = createVar();
export const rowSpan = createVar();
export const rowSpanBase = createVar();
export const rowSpanPhone = createVar();
export const rowSpanTablet = createVar();
export const rowSpanLaptop = createVar();
export const rowSpanDesktop = createVar();
export const rowSpanWide = createVar();
