import {
  animation,
  blur,
  breakpoints,
  font,
  glass,
  gray,
  palettes,
  radius,
  shadows,
  sizes,
  spacing,
  zIndex,
  type NebulaTheme,
} from "@stellaria/nebula-tokens";

export const nebulaLight = {
  meta: { name: "light", scheme: "light", version: "0.1.0" },
  palettes,
  colors: {
    ...palettes,
    primary: palettes.indigo,
    accent: palettes.violet,
    gray,
    semantic: {
      success: palettes.green,
      warning: palettes.yellow,
      error: palettes.red,
      info: palettes.blue,
    },
    surface: {
      overlay: palettes.light["50"],
      base: palettes.light["200"],
      raised: palettes.light["300"],
      sunken: palettes.light["400"],
      hover: palettes.light["300"],
      active: palettes.light["300"],
      hoverActive: palettes.light["400"],
      disabled: gray["200"],
    },
    text: {
      primary: gray["950"],
      secondary: gray["900"],
      muted: gray["800"],
      placeholder: gray["700"],
      inverted: gray["50"],
      onPrimary: palettes.light["50"],
      onGradient: palettes.light["50"],
      disabled: gray["400"],
    },
    border: {
      subtle: palettes.light["400"],
      default: palettes.light["500"],
      strong: gray["500"],
      focus: palettes.indigo["600"],
      disabled: palettes.light["700"],
    },
  },
  font,
  radius,
  spacing,
  sizes,
  motion: {
    tier: "standard",
    duration: animation.duration,
    easing: animation.easing,
    spring: animation.spring,
  },
  effects: {
    blur,
    glass: { surface: glass.surface, noiseOpacity: glass.noiseOpacity, enabled: true },
    shadows,
    gradients: {
      brand: {
        type: "linear",
        angle: 135,
        stops: [
          { color: palettes.indigo["500"], position: 0 },
          { color: palettes.violet["500"], position: 100 },
        ],
      },
      accent: {
        type: "linear",
        angle: 90,
        stops: [
          { color: palettes.violet["500"], position: 0 },
          { color: palettes.pink["500"], position: 100 },
        ],
      },
      surface: {
        type: "radial",
        angle: 0,
        stops: [
          { color: palettes.indigo["50"], position: 0 },
          { color: palettes.light["50"], position: 100 },
        ],
      },
    },
  },
  variantMap: {
    filled: { background: "scale.500", foreground: "text.onPrimary", border: "none" },
    outline: { background: "transparent", foreground: "scale.700", border: "scale.700" },
    light: { background: "scale.500.12", foreground: "scale.800", border: "none" },
    glass: {
      background: "surface.overlay",
      foreground: "text.primary",
      border: "border.subtle",
      glass: "control",
    },
    ghost: { background: "transparent", foreground: "scale.700", border: "none" },
    glow: { background: "scale.500", foreground: "text.onPrimary", border: "none", glow: "lg" },
    gradient: { background: "gradient.brand", foreground: "text.onPrimary", border: "none" },
    unstyled: { background: "transparent", foreground: "currentColor", border: "none" },
  },
  zIndex,
  breakpoints,
} satisfies NebulaTheme;
