import {
  animation,
  blur,
  breakpoints,
  font,
  glass,
  gray,
  palettes,
  shadows,
  sizes,
  spacing,
  zIndex,
  type NebulaTheme,
} from "@stellaria/nebula-tokens";

export const playful = {
  meta: { name: "playful", scheme: "light", version: "0.1.0" },
  palettes,
  colors: {
    ...palettes,
    primary: palettes.grape,
    accent: palettes.pink,
    gray,
    semantic: {
      success: palettes.green,
      warning: palettes.yellow,
      error: palettes.red,
      info: palettes.blue,
    },
    surface: {
      base: palettes.light["600"],
      raised: palettes.light["400"],
      overlay: palettes.light["50"],
      sunken: palettes.light["800"],
      hover: palettes.light["300"],
      active: palettes.light["500"],
      hoverActive: palettes.light["600"],
      disabled: palettes.light["600"],
    },
    text: {
      primary: gray["950"],
      secondary: gray["900"],
      muted: gray["800"],
      placeholder: gray["700"],
      inverted: gray["50"],
      onPrimary: palettes.light["50"],
      onGradient: palettes.light["50"],
      disabled: gray["400"],
    },
    border: {
      subtle: gray["50"],
      default: gray["100"],
      strong: gray["600"],
      focus: palettes.grape["600"],
      disabled: gray["300"],
    },
  },
  font,
  radius: { none: 0, xxs: 4, xs: 6, sm: 10, md: 16, lg: 20, xl: 28, xxl: 36, full: 9999 },
  spacing: { unit: 5, scale: spacing.scale },
  sizes,
  motion: {
    tier: "expressive",
    duration: animation.duration,
    easing: animation.easing,
    spring: animation.spring,
  },
  effects: {
    blur,
    glass: { surface: glass.surface, noiseOpacity: 0.03, enabled: true },
    shadows,
    gradients: {
      brand: {
        type: "linear",
        angle: 135,
        stops: [
          { color: palettes.grape["600"], position: 0 },
          { color: palettes.pink["600"], position: 55 },
          { color: palettes.orange["600"], position: 100 },
        ],
      },
      accent: {
        type: "linear",
        angle: 90,
        stops: [
          { color: palettes.cyan["400"], position: 0 },
          { color: palettes.lime["400"], position: 100 },
        ],
      },
      surface: {
        type: "radial",
        angle: 0,
        stops: [
          { color: palettes.pink["50"], position: 0 },
          { color: palettes.light["50"], position: 100 },
        ],
      },
    },
  },
  variantMap: {
    filled: { background: "gradient.brand", foreground: "text.onPrimary", border: "none" },
    outline: { background: "transparent", foreground: "scale.700", border: "scale.700" },
    light: { background: "scale.500.16", foreground: "scale.800", border: "none" },
    glass: {
      background: "surface.overlay",
      foreground: "text.primary",
      border: "border.subtle",
      glass: "strong",
    },
    ghost: { background: "transparent", foreground: "scale.700", border: "none" },
    glow: { background: "scale.600", foreground: "text.onPrimary", border: "none", glow: "xl" },
    gradient: { background: "gradient.accent", foreground: "text.primary", border: "none" },
    unstyled: { background: "transparent", foreground: "currentColor", border: "none" },
  },
  zIndex,
  breakpoints,
} satisfies NebulaTheme;
