import {
  animation,
  blur,
  breakpoints,
  font,
  glass,
  gray,
  palettes,
  shadows,
  sizes,
  spacing,
  zIndex,
  type NebulaTheme,
} from "@stellaria/nebula-tokens";

export const soberLight = {
  meta: { name: "sober-light", scheme: "light", version: "0.1.0" },
  palettes,
  colors: {
    ...palettes,
    primary: palettes.blue,
    accent: palettes.teal,
    gray,
    semantic: {
      success: palettes.green,
      warning: palettes.yellow,
      error: palettes.red,
      info: palettes.blue,
    },
    surface: {
      base: palettes.light["600"],
      raised: palettes.light["400"],
      overlay: palettes.light["50"],
      sunken: palettes.light["800"],
      hover: palettes.light["500"],
      active: palettes.light["600"],
      disabled: palettes.light["700"],
    },
    text: {
      primary: gray["950"],
      secondary: gray["900"],
      muted: gray["800"],
      placeholder: gray["800"],
      inverted: gray["50"],
      onPrimary: palettes.light["50"],
      disabled: gray["400"],
    },
    border: {
      subtle: gray["200"],
      default: gray["300"],
      strong: gray["700"],
      focus: palettes.blue["600"],
      disabled: gray["300"],
    },
  },
  font,
  radius: { none: 0, xxs: 0, xs: 0, sm: 2, md: 2, lg: 4, xl: 6, xxl: 8, full: 9999 },
  spacing: { unit: 3, scale: spacing.scale },
  sizes,
  motion: {
    tier: "minimal",
    duration: animation.duration,
    easing: animation.easing,
    spring: animation.spring,
  },
  effects: {
    blur,
    glass: { surface: glass.surface, noiseOpacity: 0, enabled: false },
    shadows,
    gradients: {
      brand: {
        type: "linear",
        angle: 135,
        stops: [
          { color: palettes.blue["700"], position: 0 },
          { color: palettes.blue["500"], position: 100 },
        ],
      },
      accent: {
        type: "linear",
        angle: 90,
        stops: [
          { color: palettes.teal["700"], position: 0 },
          { color: palettes.teal["500"], position: 100 },
        ],
      },
      surface: {
        type: "radial",
        angle: 0,
        stops: [
          { color: gray["50"], position: 0 },
          { color: palettes.light["50"], position: 100 },
        ],
      },
    },
  },
  variantMap: {
    filled: { background: "scale.500", foreground: "text.onPrimary", border: "none" },
    outline: { background: "transparent", foreground: "scale.800", border: "scale.700" },
    light: { background: "scale.500.10", foreground: "scale.800", border: "none" },
    glass: { background: "surface.raised", foreground: "text.primary", border: "border.default" },
    ghost: { background: "transparent", foreground: "scale.800", border: "none" },
    glow: { background: "scale.700", foreground: "text.onPrimary", border: "none" },
    gradient: { background: "scale.700", foreground: "text.onPrimary", border: "none" },
    unstyled: { background: "transparent", foreground: "currentColor", border: "none" },
  },
  zIndex,
  breakpoints,
} satisfies NebulaTheme;
