import { createThemeContract } from "@vanilla-extract/css";

const Scale = (): Record<
  "50" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900" | "950",
  null
> => ({
  "50": null,
  "100": null,
  "200": null,
  "300": null,
  "400": null,
  "500": null,
  "600": null,
  "700": null,
  "800": null,
  "900": null,
  "950": null,
});

export const vars = createThemeContract({
  color: {
    primary: Scale(),
    accent: Scale(),
    gray: Scale(),
    semantic: {
      success: Scale(),
      warning: Scale(),
      error: Scale(),
      info: Scale(),
    },
    surface: {
      base: null,
      raised: null,
      overlay: null,
      sunken: null,
      hover: null,
      active: null,
    },
    text: { primary: null, secondary: null, muted: null, inverted: null, onPrimary: null },
    border: { subtle: null, default: null, strong: null, focus: null },
  },
  font: {
    family: { sans: null, mono: null },
    size: {
      h1: null,
      h2: null,
      h3: null,
      h4: null,
      h5: null,
      h6: null,
      body1: null,
      body2: null,
      body3: null,
      button: null,
      caption: null,
    },
    weight: {
      thin: null,
      extralight: null,
      light: null,
      regular: null,
      medium: null,
      semibold: null,
      bold: null,
      extrabold: null,
      black: null,
    },
    lineHeight: { tight: null, normal: null, relaxed: null },
    letterSpacing: { tight: null, normal: null, wide: null },
  },
  radius: { xxs: null, xs: null, sm: null, md: null, lg: null, xl: null, xxl: null, full: null },
  space: {
    none: null,
    xxs: null,
    xs: null,
    u1_5: null,
    sm: null,
    u2_5: null,
    u3: null,
    u3_5: null,
    md: null,
    u5: null,
    lg: null,
    xl: null,
    xxl: null,
    xxxl: null,
  },
  size: {
    control: { xs: null, sm: null, md: null, lg: null, xl: null },
    compact: { xs: null, sm: null, md: null, lg: null, xl: null },
  },
  motion: {
    duration: { instant: null, fast: null, base: null, slow: null, expressive: null },
    easing: { standard: null, emphasized: null, decelerate: null, accelerate: null },
  },
  blur: { none: null, xxs: null, xs: null, sm: null, md: null, lg: null, xl: null, xxl: null },
  shadow: { xxs: null, xs: null, sm: null, md: null, lg: null, xl: null, xxl: null },
  glass: {
    subtle: { background: null, border: null, backdropFilter: null },
    default: { background: null, border: null, backdropFilter: null },
    strong: { background: null, border: null, backdropFilter: null },
    noiseOpacity: null,
  },
  zIndex: {
    base: null,
    dropdown: null,
    sticky: null,
    overlay: null,
    modal: null,
    popover: null,
    toast: null,
    tooltip: null,
  },
});
