import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  BarChart3,
  Bell,
  Bookmark,
  Calendar,
  Camera,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  Folder,
  Heart,
  HelpCircle,
  Home,
  Image,
  Info,
  LayoutDashboard,
  LineChart,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  Mic,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  PieChart,
  Play,
  Plus,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  Star,
  ThumbsUp,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  Users,
  Video,
  Volume2,
  Wallet,
  X,
} from "lucide-react";

import type { IconComponent } from "../types.js";

export const NavigationPack = {
  home: Home,
  menu: Menu,
  search: Search,
  settings: Settings,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "external-link": ExternalLink,
  more: MoreHorizontal,
  "more-vertical": MoreVertical,
  logout: LogOut,
} as const satisfies Record<string, IconComponent>;

export const ActionsPack = {
  plus: Plus,
  minus: Minus,
  check: Check,
  close: X,
  edit: Pencil,
  trash: Trash2,
  copy: Copy,
  save: Save,
  download: Download,
  upload: Upload,
  share: Share2,
  refresh: RefreshCw,
  filter: Filter,
  sort: ArrowUpDown,
  eye: Eye,
  "eye-off": EyeOff,
} as const satisfies Record<string, IconComponent>;

export const StatusPack = {
  info: Info,
  success: CheckCircle2,
  warning: AlertTriangle,
  error: AlertCircle,
  help: HelpCircle,
  loader: Loader2,
  bell: Bell,
} as const satisfies Record<string, IconComponent>;

export const DashboardPack = {
  dashboard: LayoutDashboard,
  "bar-chart": BarChart3,
  "line-chart": LineChart,
  "pie-chart": PieChart,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  activity: Activity,
  users: Users,
  user: User,
  calendar: Calendar,
  clock: Clock,
  wallet: Wallet,
  "credit-card": CreditCard,
  dollar: DollarSign,
} as const satisfies Record<string, IconComponent>;

export const FormsPack = {
  user: User,
  mail: Mail,
  lock: Lock,
  phone: Phone,
  calendar: Calendar,
  search: Search,
  eye: Eye,
  "eye-off": EyeOff,
  check: Check,
  "check-square": CheckSquare,
  circle: Circle,
} as const satisfies Record<string, IconComponent>;

export const MediaPack = {
  image: Image,
  video: Video,
  play: Play,
  pause: Pause,
  volume: Volume2,
  mic: Mic,
  camera: Camera,
} as const satisfies Record<string, IconComponent>;

export const FilesPack = {
  file: File,
  "file-text": FileText,
  folder: Folder,
  paperclip: Paperclip,
  download: Download,
  upload: Upload,
} as const satisfies Record<string, IconComponent>;

export const CommunicationPack = {
  mail: Mail,
  message: MessageSquare,
  send: Send,
  bell: Bell,
  heart: Heart,
  star: Star,
  bookmark: Bookmark,
  "thumbs-up": ThumbsUp,
  share: Share2,
} as const satisfies Record<string, IconComponent>;

export const CommonPack = {
  home: Home,
  menu: Menu,
  search: Search,
  settings: Settings,
  plus: Plus,
  check: Check,
  close: X,
  edit: Pencil,
  trash: Trash2,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  more: MoreHorizontal,
  info: Info,
  bell: Bell,
  user: User,
} as const satisfies Record<string, IconComponent>;

export const AllIconsPack = {
  ...NavigationPack,
  ...ActionsPack,
  ...StatusPack,
  ...DashboardPack,
  ...FormsPack,
  ...MediaPack,
  ...FilesPack,
  ...CommunicationPack,
  ...CommonPack,
} as const satisfies Record<string, IconComponent>;
