import {
  Activity,
  Anchor,
  Archive,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  BarChart3,
  Bell,
  Ban,
  Bookmark,
  Calendar,
  Camera,
  CircleX,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Coins,
  Compass,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  Folder,
  Globe,
  Heart,
  HelpCircle,
  Home,
  Image,
  Info,
  Key,
  Keyboard,
  Languages,
  Layers,
  LayoutGrid,
  LayoutDashboard,
  LineChart,
  Link2,
  List,
  LockOpen,
  LogIn,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  Menu,
  MessageSquare,
  Mic,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  PieChart,
  Play,
  Plus,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  Rss,
  Save,
  Scissors,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  Shirt,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Star,
  ThumbsUp,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  Volume2,
  VolumeX,
  WandSparkles,
  Wallet,
  X,
  Zap,
} from "lucide-react";

import type { IconComponent } from "../types.js";

export const NavigationPack = {
  home: Home,
  menu: Menu,
  search: Search,
  settings: Settings,
  compass: Compass,
  "map-pin": MapPin,
  grid: LayoutGrid,
  list: List,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "external-link": ExternalLink,
  more: MoreHorizontal,
  "more-vertical": MoreVertical,
  logout: LogOut,
} as const satisfies Record<string, IconComponent>;

export const ActionsPack = {
  plus: Plus,
  minus: Minus,
  check: Check,
  close: X,
  edit: Pencil,
  trash: Trash2,
  copy: Copy,
  save: Save,
  download: Download,
  upload: Upload,
  share: Share2,
  refresh: RefreshCw,
  filter: Filter,
  sort: ArrowUpDown,
  eye: Eye,
  "eye-off": EyeOff,
  archive: Archive,
  link: Link2,
  maximize: Maximize2,
  minimize: Minimize2,
  sliders: SlidersHorizontal,
  repeat: Repeat,
  undo: RotateCcw,
  "x-circle": CircleX,
} as const satisfies Record<string, IconComponent>;

export const StatusPack = {
  info: Info,
  success: CheckCircle2,
  warning: AlertTriangle,
  error: AlertCircle,
  help: HelpCircle,
  loader: Loader2,
  bell: Bell,
  shield: Shield,
  key: Key,
  unlock: LockOpen,
  ban: Ban,
} as const satisfies Record<string, IconComponent>;

export const DashboardPack = {
  dashboard: LayoutDashboard,
  "bar-chart": BarChart3,
  "line-chart": LineChart,
  "pie-chart": PieChart,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  activity: Activity,
  users: Users,
  user: User,
  calendar: Calendar,
  clock: Clock,
  wallet: Wallet,
  "credit-card": CreditCard,
  dollar: DollarSign,
  coins: Coins,
  receipt: Receipt,
  layers: Layers,
} as const satisfies Record<string, IconComponent>;

export const FormsPack = {
  user: User,
  mail: Mail,
  lock: Lock,
  phone: Phone,
  calendar: Calendar,
  search: Search,
  eye: Eye,
  "eye-off": EyeOff,
  check: Check,
  "check-square": CheckSquare,
  circle: Circle,
  "user-plus": UserPlus,
  login: LogIn,
  globe: Globe,
  languages: Languages,
  keyboard: Keyboard,
} as const satisfies Record<string, IconComponent>;

export const MediaPack = {
  image: Image,
  video: Video,
  play: Play,
  pause: Pause,
  volume: Volume2,
  "volume-off": VolumeX,
  "skip-forward": SkipForward,
  "skip-back": SkipBack,
  mic: Mic,
  camera: Camera,
} as const satisfies Record<string, IconComponent>;

export const FilesPack = {
  file: File,
  "file-text": FileText,
  folder: Folder,
  paperclip: Paperclip,
  download: Download,
  upload: Upload,
} as const satisfies Record<string, IconComponent>;

export const CommunicationPack = {
  mail: Mail,
  message: MessageSquare,
  send: Send,
  bell: Bell,
  heart: Heart,
  star: Star,
  bookmark: Bookmark,
  "thumbs-up": ThumbsUp,
  share: Share2,
  rss: Rss,
} as const satisfies Record<string, IconComponent>;

/**
 * El tema.
 *
 * Nebula sirve el theming y no traía con qué dibujarlo: cualquier producto con un
 * conmutador de claro y oscuro acababa poniendo una estrella o un círculo, que es lo
 * que hacía Rosette. `monitor` es la tercera opción de verdad — seguir al sistema.
 */
export const ThemePack = {
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
} as const satisfies Record<string, IconComponent>;

/**
 * Crear cosas.
 *
 * La familia que falta en un catálogo pensado para paneles: un producto que genera
 * —imágenes, escenas, vestuario— necesita nombrar el destello, la referencia que
 * sostiene una identidad y las capas de un montaje.
 */
export const CreativePack = {
  sparkles: Sparkles,
  wand: WandSparkles,
  zap: Zap,
  anchor: Anchor,
  shirt: Shirt,
  scissors: Scissors,
} as const satisfies Record<string, IconComponent>;

export const CommonPack = {
  home: Home,
  menu: Menu,
  search: Search,
  settings: Settings,
  plus: Plus,
  check: Check,
  close: X,
  edit: Pencil,
  trash: Trash2,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  more: MoreHorizontal,
  info: Info,
  bell: Bell,
  user: User,
} as const satisfies Record<string, IconComponent>;

export const AllIconsPack = {
  ...NavigationPack,
  ...ActionsPack,
  ...StatusPack,
  ...DashboardPack,
  ...FormsPack,
  ...MediaPack,
  ...FilesPack,
  ...CommunicationPack,
  ...ThemePack,
  ...CreativePack,
  ...CommonPack,
} as const satisfies Record<string, IconComponent>;
